### ISSUE TITLE
how to build and run this project?

### ISSUE THREAD

**Issue by jerryhero** [kaist-ina/Extractocol#4]
I have import the project into Eclipse,but I can't run it.Could you tell me how to build and run the project?

**Comment by appff** [comment]
Hi, jerryhero.
Can you explain your situation with screenshot and error message? I don't know what your problem is.
Actually, This repo includes an Eclipse setting file to run Extractocol simply. So if it is a right environment, you don't need to any configuration. You just import eclipse project file.
If you're uncomfortable to explain your problem in this thread, you can send email to me. (appff13@gmail.com)
Thx.

**Comment by jerryhero** [comment]
Hi, appff.

Following is my develop environment:
Eclipse 4.7.2,jdk8,ubuntu 64

I have just import this porject into Eclipse by using import existing project into Eclipse menu,then I use open the file which named "soot.jimple.infoflow.android.TestApps.java"(Its path is src/soot-infoflow-android/src/soot/jimple/infoflow/android/TestApps/Test.java).I just use the menu run as but found it only has "run configurations".So I enter into the menu of "run configurations",but there is no launch configuration.I just add one "launch configuration" which type is "java application",but it show the error of "Main type not specified" and I can't set the item of project.

Did I do something wrong?Could you tell me how to run it after importing the project into Eclipse?Thanks a lot!

**Comment by appff** [comment]
First of all, the uploaded Eclipse project file is for windows. Maybe...
As your mentioned, you should create a new configuration file. For building
network signatures, you should run a main method in
Extractocol.Tester.BackendTester_Request class.
Detail information is avaliable in
https://github.com/kaist-ina/Extractocol_public#how-to.
Regards, Jeongmin.

2018년 7월 12일 (목) 오후 5:20, jerryhero <notifications@github.com>님이 작성:

**Comment by appff** [comment]
Sorry for late reply.

Actually, Extractocol performs program slicing at method level. So if you
want to get program slice including program statements, you should modify
Extractocol or Flowdroid.
If you want to use taint rules of Extractocol, you modify Extractocol.
otherwise, you should modify Flowdroid.
In modifying Flowdroid, you not only add program slicing feature into
Flowdroid but also make Flowdroid consider only sink or source.

See this code - IFDSSolver.java

Regards, Jeongmin

2018년 7월 13일 (금) 오후 4:27, jerryhero <notifications@github.com>님이 작성:
